version: "3"

services:
  simple-docker-proxy:
    image: dimdm/simple-docker-proxy:arm32v6
    container_name: simple-docker-proxy
    expose:
      - 1234/tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
  radapi:
    image: dimdm/radapi:arm32v6
    container_name: radapi
    expose:
      - 1880/tcp
    ports:
      - 0.0.0.0:1880:1880/tcp
    links:
      - simple-docker-proxy
    volumes:
      - radapi_data:/radapi/data:rw

volumes:
  radapi_data:
    driver: local
