version: "3"

services:
  elasticsearch:
    image: elasticsearch:alpine
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"

  logstash:
    image: dimdm/logstash
    container_name: logstash
    links:
      - elasticsearch
    ports:
      - "12201:12201/udp"

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    depends_on:
      - logstash
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"

  redis-commander:
    image: dimdm/redis-commander
    container_name: redis-commander
    ports:
      - "8081:8081"
    links:
      - redis
    depends_on:
      - logstash
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"

  influxdb:
    image: influxdb:alpine
    container_name: influxdb
    ports:
      - "8086:8086"
      - "8096:8096/udp"
    depends_on:
      - logstash
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    depends_on:
      - logstash
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"

  arangodb:
    image: arangodb
    container_name: arangodb
    environment:
      - ARANGO_NO_AUTH=1
    ports:
      - "8529:8529"
    depends_on:
      - logstash
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"

  rethinkdb:
    image: rethinkdb
    container_name: rethinkdb
    ports:
      - "8080:8080"
      - "28015:28015"
      - "29015:29015"
    depends_on:
      - logstash
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"

  postgres:
    image: postgres:alpine
    container_name: postgres
    ports:
      - "5432:5432"
    depends_on:
      - logstash
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"

  pgadmin:
    image: thajeztah/pgadmin4
    container_name: pgadmin
    links:
      - postgres
    ports:
      - "5050:5050"
    depends_on:
      - logstash
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"

  cockroachdb:
    image: cockroachdb/cockroach
    container_name: cockroachdb
    ports:
      - "26257:26257"
      - "8082:8080"
    depends_on:
      - logstash
    command:
      - "start"
      - "--insecure"
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"

  radapi:
    image: dimdm/radapi
    container_name: radapi
    links:
      - prometheus
      - arangodb
      - cockroachdb
      - rethinkdb
      - postgres
      - redis
      - influxdb
      - elasticsearch
    volumes:
      - code_volume:/opt/radapi
    ports:
      - "1880:1880"
    depends_on:
      - logstash
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"

  c9:
    image: dimdm/c9
    container_name: c9
    volumes:
      - code_volume:/opt/radapi
    ports:
      - "8181:8181"
      - "8282:8282"
    depends_on:
      - logstash
      - radapi
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"

  notebook:
    image: dimdm/notebook
    container_name: notebook
    links:
      - prometheus
      - arangodb
      - cockroachdb
      - rethinkdb
      - postgres
      - redis
      - influxdb
      - elasticsearch
      - radapi
    ports:
      - "8888:8888"
    depends_on:
      - logstash
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"

  etherpad:
    image: dimdm/etherpad
    container_name: etherpad
    ports:
      - "9001:9001"
    depends_on:
      - logstash
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"

  grafana:
    image: grafana/grafana
    container_name: grafana
    links:
      - influxdb
    ports:
      - "3000:3000"

  kibana:
    image: kibana
    container_name: kibana
    links:
      - elasticsearch
    ports:
      - "5601:5601"

  weave:
    image: weaveworks/scope
    container_name: weave
    privileged: true
    pid: "host"
    labels:
      - "works.weave.role=system"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
    environment:
      - CHECKPOINT_DISABLE=true
    command:
      - "--probe.docker"
      - "true"
    ports:
      - "4040:4040"

volumes:
  code_volume:
